In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import time

In [2]:
model_path = '/project/lt200301-edubot/Capstone-TamTanai/models/finetuned_mpnet'
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

In [3]:
model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

XLMRobertaForSequenceClassification(
  (roberta): XLMRobertaModel(
    (embeddings): XLMRobertaEmbeddings(
      (word_embeddings): Embedding(250002, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): XLMRobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x XLMRobertaLayer(
          (attention): XLMRobertaAttention(
            (self): XLMRobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): XLMRobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=

In [24]:
prompt = '''ขับรถชนคนผิดหรือไม่'''

encodings = tokenizer(prompt, truncation=True, padding=True, max_length=512, return_tensors='pt')
input_ids = encodings['input_ids'].to(device)
attention_mask = encodings['attention_mask'].to(device)
with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
    logit = outputs.logits[0]
    print(logit)
    predictions = torch.argmax(logits, dim=-1).cpu().numpy()
    probabilities = torch.softmax(logits, dim=-1).cpu().numpy()
probabilities

tensor([-4.1820,  4.3582], device='cuda:0')


array([[1.9541591e-04, 9.9980456e-01]], dtype=float32)

In [14]:
text = 'ขับรถชนคนผิดหรือไม่'

encodings = tokenizer(text, truncation=True, padding=True, max_length=512, return_tensors='pt')
input_ids = encodings['input_ids'].to(device)
attention_mask = encodings['attention_mask'].to(device)
with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
logits = outputs.logits
prediction = torch.argmax(logits, dim=-1).cpu().numpy()[0]
prediction = int(prediction)
probability = torch.softmax(logits, dim=-1).cpu().numpy()[0][1]
probability = float(probability)
prediction, probability

(1, 0.9998045563697815)

In [13]:
probability = torch.softmax(logits, dim=-1).cpu().numpy()[0][1]
probability = float(probability)
probability

0.9998045563697815

In [40]:
int(torch.argmax(logits, dim=-1).cpu().numpy()[0])

1

In [26]:
logits

tensor([[-4.1820,  4.3582]], device='cuda:0')

In [28]:
predictions[0]

np.int64(1)